---
galaxy_info:
  author: Pedro Verissimo
  description: Essa role do Ansible prove inumeras medidas de segiranca.'
  company: ''
  license: Apache License 2.0
  min_ansible_version: '2.5'
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Ubuntu
      versions:
        - xenial
        - bionic
    - name: Debian
      versions:
        - jessie
    - name: Amazon
    - name: Fedora
  galaxy_tags:
    - system
    - security
    - hardening
dependencies: []
