- name: Playbook para hardening AWS - CriptoPayShop
  hosts: aws
  become: true
  roles:
    - hardening_os
    - hardening_ssh
  vars:
    sysctl_overwrite:
      net.ipv4.ip_forward: 1
      net.ipv4.tcp_syncookies: 1
      net.ipv4.conf.all.accept_redirects: 0
      net.ipv4.conf.all.send_redirects: 0
      net.ipv4.conf.all.rp_filter: 1
      net.ipv4.icmp_echo_ignore_broadcasts: 1
      net.ipv4.icmp_ignore_bogus_error_responses: 1
      net.ipv4.conf.all.bootp_relay: 1
      net.ipv4.tcp_max_syn_backlog: 2048
    os_security_immutable_enforce: true
    os_security_immutable_blacklist:
      - /etc/passwd
      - /etc/group
      - /etc/gshadow
      - /etc/shadow
      - /etc/services
      - /etc/sudoers
    os_security_init_single: true
    os_auth_root_ttys: [console, tty1, tty2, tty3]
